services:
  web:
    command: uvicorn app.web:app --factory --host 0.0.0.0 --reload
    restart: "no"
    env_file: .env.dev
    volumes:
      - ./app:/aa-api/app # for --reload to work
    environment:
      - ENVIRONMENT_FILE=.env.dev
      - SERVE_LOCAL_ARCHIVE=/aa-api/app/local_archive # See orchestration.yaml local_storage.save_to
      - ALLOWED_ORIGINS=["http://localhost:8000","http://localhost:8004","http://localhost:8081","chrome-extension://ojcimmjndnlmmlgnjaeojoebaceokpdp"]
      - USER_GROUPS_FILENAME=/aa-api/app/user-groups.dev.yaml
      - DATABASE_PATH=sqlite:////aa-api/database/auto-archiver.db
    

  worker:
    command: watchmedo auto-restart --patterns="*.py" --recursive --ignore-directories -- celery -- --app=app.worker.main.celery worker --loglevel=debug --logfile=/aa-api/logs/celery.log -Q high_priority,low_priority --concurrency=$CONCURRENCY
    restart: "no"
    env_file: .env.dev
    volumes:
      - ./app:/aa-api/app # for watchmedo

  redis:
    restart: "no"
    env_file: .env.dev
    ports:
      - 6379:6379
