version: '3.8'

services:
  web:
    environment:
      - SERVE_LOCAL_ARCHIVE=/app/local_archive # See orchestration.yaml local_storage.save_to
      - ALLOWED_ORIGINS=http://localhost:8004
  redis:
    command: redis-server /conf/redis.conf
    ports:
      - 6379:6379
