services:
  web:
    restart: "no"
    env_file: src/.env.dev
    environment:
      - SERVE_LOCAL_ARCHIVE=/app/local_archive # See orchestration.yaml local_storage.save_to
      - ALLOWED_ORIGINS=http://localhost:8004,chrome-extension://ojcimmjndnlmmlgnjaeojoebaceokpdp
      - API_BEARER_TOKEN=dev-api-bearer-token
      - USER_GROUPS_FILENAME=user-groups.dev.yaml

  worker:
    restart: "no"
    env_file: src/.env.dev

  redis:
    restart: "no"
    env_file: src/.env.dev
    ports:
      - 6379:6379
